Feature/jc 646 initialize anime app and table view
saritasa-nest/camp-js-2024-andrey-strokan pull request #3
Opened 2024-08-15 21:55 UTC by Andrey-Strokan

2024-08-16 09:43 UTC, viktor-sakhno-saritasa requested changes

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/DTOs/AiredDTO.ts
> +};
Pls, revise code for adding missed `readonly` modifiers.
```suggestion
export type AiredDTO = {

	/** Start. */
	readonly start: string;

	/** End. */
	readonly end: string | null;
};
```

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/DTOs/AiredDTO.ts
Pls, check this [wiki article ](https://wiki.saritasa.rocks/frontend/frameworks/architecture/), you can find our approach about files and types naming.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.html
> +				<img [src]="element.imageSourceURL" alt="{{element.titleEnglish}}" class="image"/>
```suggestion
				<img [src]="element.imageSourceURL" [alt]="element.titleEnglish" class="image"/>
```

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.css
> +}
It looks like a common style for images.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	public displayedColumns: string[] = ['imageSourceURL', 'titleEnglish', 'titleJapan', 'airedStart', 'filmType', 'filmStatus'];
1. Don't forget about readonly;
2. We prefer to use `protected` modifier for properties that using in template.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	public constructor(private apiService: ApiService) {}
Let's use a modern approach to inject dependencies.
```suggestion
	private readonly apiService = inject(ApiService);
```

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	public constructor(private apiService: ApiService) {}
Also, it's bad practice to use such words like `Api, Http`, etc. inside our components. It would be better to rename this service to `AnimeService`, for example.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +				},
Your way breaks reactive approach. We shouldn't mutate our variables where it is possible and should work with `Observable` directly.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +				} as AnimeFilm))),
We should do all mapping operations inside our services, it's not component responsibility.

2024-08-16 09:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/entities/animeFilm.ts
> +	filmStatus: string;
I believe, `film` prefix is redundant, because our type's name is `AnimeFilm`.

2024-08-19 08:35 UTC, DaniilMaslovSaritasa approved these changes

2024-08-19 08:35 UTC, DaniilMaslovSaritasa commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	public displayedColumns: string[] = ['imageSourceURL', 'titleEnglish', 'titleJapan', 'airedStart', 'filmType', 'filmStatus'];
```suggestion
	protected displayedColumns = ['imageSourceURL', 'titleEnglish', 'titleJapan', 'airedStart', 'filmType', 'filmStatus'] as const;
```
We prefer to calculate types using typescript where possible

2024-08-23 06:26 UTC, viktor-sakhno-saritasa approved these changes

2024-08-26 04:31 UTC, pavel-romanov8 requested changes

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.css
> +img {
We're trying to use [BEM](https://en.bem.info/methodology/naming-convention/) naming convention for our CSS classes. It prohibits the usage of HTML tags and promotes a class-based approach. It would be great if we can stick to it through the camp as well

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.html
> +		<td mat-cell *matCellDef="let element">
Since we're working with anime we can give a more meaningful names to cell definitions
```suggestion
		<td mat-cell *matCellDef="let anime">
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.html
> +		<th mat-header-cell *matHeaderCellDef>Title (Japan)</th>
I believe that the column is related to the title's language. In this case, `Japan` is the name of the country, not of the language. It would be more appropriate to use `Japanese` instead. We're following the same logic with the English title, where we declare the language name but not the country (England).
```suggestion
		<th mat-header-cell *matHeaderCellDef>Title (Japanese)</th>
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.html
> +<table mat-table [dataSource]="(allAnime$ | async) ?? []">
Usually, we provide the `trackBy` function when we're using `mat-table` to make it more optimized. You can read more about the [material table API](https://material.angular.io/cdk/table/api#CdkTable) on their website.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	/** Services. */
It is a single service
```suggestion
	/** Service. */
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.ts
> +	private readonly apiService = inject(AnimeService);
The name is too generic. Let's try to be consistent and provide more specific names like we do it with the list of anime

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/aired.dto.ts
> +export type AiredDto = {
This model shouldn't be focused specifically on some "aired" abstractions. I believe that it represents the range of dates and there is no benefit of making it tightly coupled with some "aired" abstraction. It could be just range of dates.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/aired.dto.ts
> +	readonly end: string | null;
Does the BE really send `null` of there is no end date? Most of the time they don't send anything. If that the case, then type declaration is incorrect and we should use optional fields instead.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/allAnimeResponse.dto.ts
> +export type AllAnimeResponseDto = {
From the shape of the object, I can tell it is a pagination wrapper that contains the list of _some_ items. We're describing the DTO in a non-extendable way. We won't be able to use this abstraction with anything except animes.

Instead, we can create more flexible types with generic and proper naming to show that some abstraction is only related to pagination and the other one only to anime.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Created. */
It would be great to provide a more extensive documentation whenever possible, that why we're doing it. In this case, we could provide an examples of how this date string looks like. You can check how it looks like [here](https://jsdoc.app/tags-example)

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	readonly modified: string;
From the description, it is not clear what "modified" is. Documentation is not for copying and pasting field names but for additional context. I assume that this field indicates the date of last modification, but from the naming and documentation alone it is not possible to be 100% sure.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Title english. */
```suggestion
	/** English title. */
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Title Japan. */
```suggestion
	/** Japanese title. */
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Image Url. */
```suggestion
	/** Image URL. */
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Score. */
We can provide more context behind these score fields as well

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/entities/anime.ts
> +	status: string;
We're trying to keep our structures immutable, if there is no plan to mutate any of the `Anime` objects then we can declare it as read-only

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +			} as Anime))),
Why are we using type casting?

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +				imageSourceURL: item.image,
We create a dedicated abstraction for such things called `mapper`. You can check the [architecture section](https://wiki.saritasa.rocks/frontend/frameworks/architecture/) on our wiki page.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +	private apiUrl = 'https://api.camp-js.saritasa.rocks';
Please, don't put such URLs inside of a specific service. It would be extremely hard to track them through the application. Instead, try to concentrate global variables and API URLs in the environment variables.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +	public constructor(private http: HttpClient) {}
I see that in a component, you're using the `inject` function to inject dependencies, but here, you're doing so with the constructor. Please try to stick to one approach and make it consistent throughout the application.

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +	private allAnimeEndpoint = 'api/v1/anime/anime/';
I believe we don't want to mutate this field
```suggestion
	private readonly allAnimeEndpoint = 'api/v1/anime/anime/';
```

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/index.html
> +</head>
Something wrong with indentations here

2024-08-26 04:31 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/allAnimeResponse.dto.ts
> +import { AnimeDto } from './anime.dto';
Please, follow kebab-case naming for angular-related files

2024-08-27 00:42 UTC, Andrey-Strokan commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.css
> +img {
![image](https://github.com/user-attachments/assets/ec527fb5-8007-4e1a-97ed-296953fbbcaf)

2024-08-27 00:50 UTC, Andrey-Strokan commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.css
> +img {
Fixed

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/anime.dto.ts
> +	/** Date and time of last edit of the entry. */
This version is a lot better 👍 

We can also provide an example of the date format:
```typescript

/**
 * Date and time of the last entry edit.
 * @example 2024-08-01
 */
readonly created: string;
```

P.S. The date format here is just an example

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/dto/date-range.dto.ts
> +	/** End. */
If there is some business context behind the optional field it would be great to mention it as well. For example, there is no end date because the process is ongoing and don't have a determined final date

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/entities/anime.ts
> +	/** Title english. */
```suggestion
	/** English title. */
```

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/mappers/baseClasses/mapper-base.ts
> +export abstract class MapperBase<TDto, TDomain> {
I'm still concerned about the implementation of a mapper as an abstract class. Could you please provide some reasoning behind why you've decided to do so?

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/mappers/anime.mapper.ts
> +export class AnimeMapper extends MapperBase<AnimeDto, Anime> {
Usually, we're making mappers injectable into DI by decorating them via `Injectable` decorator (in the same way as we do with services). That way, we can keep only a single instance of a class across the whole application instead of creating it manually everytime.

2024-08-29 04:44 UTC, pavel-romanov8 commented on apps/angular/src/app/services/anime.service.ts
> +import { map } from 'rxjs/operators';
We can import `map` operator from `rxjs` directly

2024-09-03 03:39 UTC, pavel-romanov8 approved these changes
Please, check the linter errors before merging

2024-09-03 03:39 UTC, pavel-romanov8 commented on apps/angular/src/app/anime-dashboard/anime-dashboard.component.html
> +				<img class="image" [src]="anime.imageSourceURL" [alt]="anime.titleEnglish"/>
You can use `ngSrc` directive instead to rip the [benefits of image optimization](https://angular.dev/guide/image-optimization)

2024-09-03 03:39 UTC, pavel-romanov8 commented on apps/angular/src/app/mappers/anime.mapper.ts
> +			modified: '',
Is it correct mapping? If there were creation or modification dates, we simply re-write them

2024-09-03 07:23 UTC, merged